//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  project: Project;
  projectConnection: ProjectConnection;
  log: Log;
  logConnection: LogConnection;
  pageContent: PageContent;
  pageContentConnection: PageContentConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryProjectArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryProjectConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProjectFilter>;
};


export type QueryLogArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryLogConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<LogFilter>;
};


export type QueryPageContentArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPageContentConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PageContentFilter>;
};

export type DocumentFilter = {
  project?: InputMaybe<ProjectFilter>;
  log?: InputMaybe<LogFilter>;
  pageContent?: InputMaybe<PageContentFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Project | Log | PageContent | Folder;

export type Project = Node & Document & {
  __typename?: 'Project';
  expId: Scalars['String']['output'];
  title_zh: Scalars['String']['output'];
  title_en: Scalars['String']['output'];
  status: Scalars['String']['output'];
  description_zh?: Maybe<Scalars['String']['output']>;
  description_en?: Maybe<Scalars['String']['output']>;
  href?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ProjectFilter = {
  expId?: InputMaybe<StringFilter>;
  title_zh?: InputMaybe<StringFilter>;
  title_en?: InputMaybe<StringFilter>;
  status?: InputMaybe<StringFilter>;
  description_zh?: InputMaybe<StringFilter>;
  description_en?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
};

export type ProjectConnectionEdges = {
  __typename?: 'ProjectConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Project>;
};

export type ProjectConnection = Connection & {
  __typename?: 'ProjectConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ProjectConnectionEdges>>>;
};

export type LogDetails = {
  __typename?: 'LogDetails';
  text_zh?: Maybe<Scalars['String']['output']>;
  text_en?: Maybe<Scalars['String']['output']>;
};

export type Log = Node & Document & {
  __typename?: 'Log';
  dateLabel: Scalars['String']['output'];
  fullDate?: Maybe<Scalars['String']['output']>;
  title_zh: Scalars['String']['output'];
  title_en: Scalars['String']['output'];
  description_zh?: Maybe<Scalars['String']['output']>;
  description_en?: Maybe<Scalars['String']['output']>;
  details?: Maybe<Array<Maybe<LogDetails>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type LogDetailsFilter = {
  text_zh?: InputMaybe<StringFilter>;
  text_en?: InputMaybe<StringFilter>;
};

export type LogFilter = {
  dateLabel?: InputMaybe<StringFilter>;
  fullDate?: InputMaybe<StringFilter>;
  title_zh?: InputMaybe<StringFilter>;
  title_en?: InputMaybe<StringFilter>;
  description_zh?: InputMaybe<StringFilter>;
  description_en?: InputMaybe<StringFilter>;
  details?: InputMaybe<LogDetailsFilter>;
};

export type LogConnectionEdges = {
  __typename?: 'LogConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Log>;
};

export type LogConnection = Connection & {
  __typename?: 'LogConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<LogConnectionEdges>>>;
};

export type PageContentSections = {
  __typename?: 'PageContentSections';
  sectionId: Scalars['String']['output'];
  label_zh?: Maybe<Scalars['String']['output']>;
  label_en?: Maybe<Scalars['String']['output']>;
  title_zh?: Maybe<Scalars['String']['output']>;
  title_en?: Maybe<Scalars['String']['output']>;
  subtitle_zh?: Maybe<Scalars['String']['output']>;
  subtitle_en?: Maybe<Scalars['String']['output']>;
  body_zh?: Maybe<Scalars['String']['output']>;
  body_en?: Maybe<Scalars['String']['output']>;
};

export type PageContent = Node & Document & {
  __typename?: 'PageContent';
  pageId: Scalars['String']['output'];
  sections?: Maybe<Array<Maybe<PageContentSections>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PageContentSectionsFilter = {
  sectionId?: InputMaybe<StringFilter>;
  label_zh?: InputMaybe<StringFilter>;
  label_en?: InputMaybe<StringFilter>;
  title_zh?: InputMaybe<StringFilter>;
  title_en?: InputMaybe<StringFilter>;
  subtitle_zh?: InputMaybe<StringFilter>;
  subtitle_en?: InputMaybe<StringFilter>;
  body_zh?: InputMaybe<StringFilter>;
  body_en?: InputMaybe<StringFilter>;
};

export type PageContentFilter = {
  pageId?: InputMaybe<StringFilter>;
  sections?: InputMaybe<PageContentSectionsFilter>;
};

export type PageContentConnectionEdges = {
  __typename?: 'PageContentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<PageContent>;
};

export type PageContentConnection = Connection & {
  __typename?: 'PageContentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PageContentConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateProject: Project;
  createProject: Project;
  updateLog: Log;
  createLog: Log;
  updatePageContent: PageContent;
  createPageContent: PageContent;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateProjectArgs = {
  relativePath: Scalars['String']['input'];
  params: ProjectMutation;
};


export type MutationCreateProjectArgs = {
  relativePath: Scalars['String']['input'];
  params: ProjectMutation;
};


export type MutationUpdateLogArgs = {
  relativePath: Scalars['String']['input'];
  params: LogMutation;
};


export type MutationCreateLogArgs = {
  relativePath: Scalars['String']['input'];
  params: LogMutation;
};


export type MutationUpdatePageContentArgs = {
  relativePath: Scalars['String']['input'];
  params: PageContentMutation;
};


export type MutationCreatePageContentArgs = {
  relativePath: Scalars['String']['input'];
  params: PageContentMutation;
};

export type DocumentUpdateMutation = {
  project?: InputMaybe<ProjectMutation>;
  log?: InputMaybe<LogMutation>;
  pageContent?: InputMaybe<PageContentMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  project?: InputMaybe<ProjectMutation>;
  log?: InputMaybe<LogMutation>;
  pageContent?: InputMaybe<PageContentMutation>;
};

export type ProjectMutation = {
  expId?: InputMaybe<Scalars['String']['input']>;
  title_zh?: InputMaybe<Scalars['String']['input']>;
  title_en?: InputMaybe<Scalars['String']['input']>;
  status?: InputMaybe<Scalars['String']['input']>;
  description_zh?: InputMaybe<Scalars['String']['input']>;
  description_en?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
};

export type LogDetailsMutation = {
  text_zh?: InputMaybe<Scalars['String']['input']>;
  text_en?: InputMaybe<Scalars['String']['input']>;
};

export type LogMutation = {
  dateLabel?: InputMaybe<Scalars['String']['input']>;
  fullDate?: InputMaybe<Scalars['String']['input']>;
  title_zh?: InputMaybe<Scalars['String']['input']>;
  title_en?: InputMaybe<Scalars['String']['input']>;
  description_zh?: InputMaybe<Scalars['String']['input']>;
  description_en?: InputMaybe<Scalars['String']['input']>;
  details?: InputMaybe<Array<InputMaybe<LogDetailsMutation>>>;
};

export type PageContentSectionsMutation = {
  sectionId?: InputMaybe<Scalars['String']['input']>;
  label_zh?: InputMaybe<Scalars['String']['input']>;
  label_en?: InputMaybe<Scalars['String']['input']>;
  title_zh?: InputMaybe<Scalars['String']['input']>;
  title_en?: InputMaybe<Scalars['String']['input']>;
  subtitle_zh?: InputMaybe<Scalars['String']['input']>;
  subtitle_en?: InputMaybe<Scalars['String']['input']>;
  body_zh?: InputMaybe<Scalars['String']['input']>;
  body_en?: InputMaybe<Scalars['String']['input']>;
};

export type PageContentMutation = {
  pageId?: InputMaybe<Scalars['String']['input']>;
  sections?: InputMaybe<Array<InputMaybe<PageContentSectionsMutation>>>;
};

export type ProjectPartsFragment = { __typename: 'Project', expId: string, title_zh: string, title_en: string, status: string, description_zh?: string | null, description_en?: string | null, href?: string | null };

export type LogPartsFragment = { __typename: 'Log', dateLabel: string, fullDate?: string | null, title_zh: string, title_en: string, description_zh?: string | null, description_en?: string | null, details?: Array<{ __typename: 'LogDetails', text_zh?: string | null, text_en?: string | null } | null> | null };

export type PageContentPartsFragment = { __typename: 'PageContent', pageId: string, sections?: Array<{ __typename: 'PageContentSections', sectionId: string, label_zh?: string | null, label_en?: string | null, title_zh?: string | null, title_en?: string | null, subtitle_zh?: string | null, subtitle_en?: string | null, body_zh?: string | null, body_en?: string | null } | null> | null };

export type ProjectQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ProjectQuery = { __typename?: 'Query', project: { __typename: 'Project', id: string, expId: string, title_zh: string, title_en: string, status: string, description_zh?: string | null, description_en?: string | null, href?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ProjectConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProjectFilter>;
}>;


export type ProjectConnectionQuery = { __typename?: 'Query', projectConnection: { __typename?: 'ProjectConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ProjectConnectionEdges', cursor: string, node?: { __typename: 'Project', id: string, expId: string, title_zh: string, title_en: string, status: string, description_zh?: string | null, description_en?: string | null, href?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type LogQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type LogQuery = { __typename?: 'Query', log: { __typename: 'Log', id: string, dateLabel: string, fullDate?: string | null, title_zh: string, title_en: string, description_zh?: string | null, description_en?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, details?: Array<{ __typename: 'LogDetails', text_zh?: string | null, text_en?: string | null } | null> | null } };

export type LogConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<LogFilter>;
}>;


export type LogConnectionQuery = { __typename?: 'Query', logConnection: { __typename?: 'LogConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'LogConnectionEdges', cursor: string, node?: { __typename: 'Log', id: string, dateLabel: string, fullDate?: string | null, title_zh: string, title_en: string, description_zh?: string | null, description_en?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, details?: Array<{ __typename: 'LogDetails', text_zh?: string | null, text_en?: string | null } | null> | null } | null } | null> | null } };

export type PageContentQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PageContentQuery = { __typename?: 'Query', pageContent: { __typename: 'PageContent', id: string, pageId: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, sections?: Array<{ __typename: 'PageContentSections', sectionId: string, label_zh?: string | null, label_en?: string | null, title_zh?: string | null, title_en?: string | null, subtitle_zh?: string | null, subtitle_en?: string | null, body_zh?: string | null, body_en?: string | null } | null> | null } };

export type PageContentConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PageContentFilter>;
}>;


export type PageContentConnectionQuery = { __typename?: 'Query', pageContentConnection: { __typename?: 'PageContentConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PageContentConnectionEdges', cursor: string, node?: { __typename: 'PageContent', id: string, pageId: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, sections?: Array<{ __typename: 'PageContentSections', sectionId: string, label_zh?: string | null, label_en?: string | null, title_zh?: string | null, title_en?: string | null, subtitle_zh?: string | null, subtitle_en?: string | null, body_zh?: string | null, body_en?: string | null } | null> | null } | null } | null> | null } };

export const ProjectPartsFragmentDoc = gql`
    fragment ProjectParts on Project {
  __typename
  expId
  title_zh
  title_en
  status
  description_zh
  description_en
  href
}
    `;
export const LogPartsFragmentDoc = gql`
    fragment LogParts on Log {
  __typename
  dateLabel
  fullDate
  title_zh
  title_en
  description_zh
  description_en
  details {
    __typename
    text_zh
    text_en
  }
}
    `;
export const PageContentPartsFragmentDoc = gql`
    fragment PageContentParts on PageContent {
  __typename
  pageId
  sections {
    __typename
    sectionId
    label_zh
    label_en
    title_zh
    title_en
    subtitle_zh
    subtitle_en
    body_zh
    body_en
  }
}
    `;
export const ProjectDocument = gql`
    query project($relativePath: String!) {
  project(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ProjectParts
  }
}
    ${ProjectPartsFragmentDoc}`;
export const ProjectConnectionDocument = gql`
    query projectConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ProjectFilter) {
  projectConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ProjectParts
      }
    }
  }
}
    ${ProjectPartsFragmentDoc}`;
export const LogDocument = gql`
    query log($relativePath: String!) {
  log(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...LogParts
  }
}
    ${LogPartsFragmentDoc}`;
export const LogConnectionDocument = gql`
    query logConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: LogFilter) {
  logConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...LogParts
      }
    }
  }
}
    ${LogPartsFragmentDoc}`;
export const PageContentDocument = gql`
    query pageContent($relativePath: String!) {
  pageContent(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PageContentParts
  }
}
    ${PageContentPartsFragmentDoc}`;
export const PageContentConnectionDocument = gql`
    query pageContentConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PageContentFilter) {
  pageContentConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PageContentParts
      }
    }
  }
}
    ${PageContentPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      project(variables: ProjectQueryVariables, options?: C): Promise<{data: ProjectQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectQueryVariables, query: string}> {
        return requester<{data: ProjectQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectQueryVariables, query: string}, ProjectQueryVariables>(ProjectDocument, variables, options);
      },
    projectConnection(variables?: ProjectConnectionQueryVariables, options?: C): Promise<{data: ProjectConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectConnectionQueryVariables, query: string}> {
        return requester<{data: ProjectConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectConnectionQueryVariables, query: string}, ProjectConnectionQueryVariables>(ProjectConnectionDocument, variables, options);
      },
    log(variables: LogQueryVariables, options?: C): Promise<{data: LogQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LogQueryVariables, query: string}> {
        return requester<{data: LogQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LogQueryVariables, query: string}, LogQueryVariables>(LogDocument, variables, options);
      },
    logConnection(variables?: LogConnectionQueryVariables, options?: C): Promise<{data: LogConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LogConnectionQueryVariables, query: string}> {
        return requester<{data: LogConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LogConnectionQueryVariables, query: string}, LogConnectionQueryVariables>(LogConnectionDocument, variables, options);
      },
    pageContent(variables: PageContentQueryVariables, options?: C): Promise<{data: PageContentQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageContentQueryVariables, query: string}> {
        return requester<{data: PageContentQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageContentQueryVariables, query: string}, PageContentQueryVariables>(PageContentDocument, variables, options);
      },
    pageContentConnection(variables?: PageContentConnectionQueryVariables, options?: C): Promise<{data: PageContentConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageContentConnectionQueryVariables, query: string}> {
        return requester<{data: PageContentConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageContentConnectionQueryVariables, query: string}, PageContentConnectionQueryVariables>(PageContentConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  