import config from "../../../../tina/config";
// @ts-expect-error - Generated by Tina CMS build
import schemaJson from "../../../../tina/__generated__/schema.json";
import { TinaAdmin } from "tinacms";

export default function AdminPage() {
  return <TinaAdmin config={config} schemaJson={schemaJson} />;
}
